travel/src/main/java/com/zerobase/travel/controller/ReportingController.java, travel/src/main/java/com/zerobase/travel/dto/request/ReportingRequestDto.java, travel/src/main/java/com/zerobase/travel/entity/ReportingEntity.java, travel/src/main/java/com/zerobase/travel/repository/ReportingRepository.java, travel/src/main/java/com/zerobase/travel/service/ReportingService.java, travel/src/test/java/com/zerobase/travel/controller/ReportingControllerTest.java, travel/src/test/java/com/zerobase/travel/service/ReportingServiceTest.java
#16 
**AS-IS**
**TO-BE**
- 사용자 신고 기능 개발
- 사용자 신고 기능 테스트 코드 개발
=> feat : 사용자 신고 기능 개발

travel/src/main/java/com/zerobase/travel/controller/FileController.java, travel/src/main/java/com/zerobase/travel/dto/response/FileResponseDto.java, travel/src/main/java/com/zerobase/travel/util/FileUtil.java, travel/src/main/resources/application.yml
#13 
**AS-IS**
**TO-BE**
파일 업로드 기능 개발
=> feat : 파일 업로드 기능 개발

travel/src/main/java/com/zerobase/travel/util/FileUtil.java
**AS-IS**
파일 저장 시 폴더 미생성
**TO-BE**
파일 저장 시 폴더 생성하도록 수정
=> feat : save 시 폴더 생성하도록 수정

travel/src/main/java/com/zerobase/travel/controller/FileController.java, travel/src/main/java/com/zerobase/travel/util/FileUtil.java
#14 
**AS-IS**
**TO-BE**
- 파일 다운로드 기능 개발
- fileUtil 에 원본 파일명 가져오는 메소드 추가
=> feat : 파일 다운로드 기능 개발

travel/src/main/java/com/zerobase/travel/controller/FileController.java, travel/src/main/resources/application.yml
#15 
**AS-IS**
**TO-BE**
- 1개의 파일 최대 용량 10MB
- 한번에 올릴수 있는 최대 용량 30MB
- 파일 미리보기 기능 개발
-
=> feat : 파일 미리보기 개발

travel/src/main/java/com/zerobase/travel/controller/VoteController.java, travel/src/main/java/com/zerobase/travel/dto/response/VoteResponseDto.java, travel/src/main/java/com/zerobase/travel/entity/VotingStartEntity.java, travel/src/main/java/com/zerobase/travel/repository/VotingStartRepository.java, travel/src/main/java/com/zerobase/travel/service/VoteService.java, travel/src/test/java/com/zerobase/travel/service/VoteServiceTest.java
#41 
**AS-IS**
**TO-BE**
- 투표 개시 상화 조회 개발
- VotingStartEntity postId 유니크 처리
- 투표 개시 상화 조회 테스트 코드 작성
=> feat : 투표 개시 상황 조회

travel/src/main/java/com/zerobase/travel/controller/VoteController.java, travel/src/main/java/com/zerobase/travel/dto/request/VoteRequestDto.java, travel/src/main/java/com/zerobase/travel/entity/VotingEntity.java, travel/src/main/java/com/zerobase/travel/repository/VotingRepository.java, travel/src/main/java/com/zerobase/travel/service/VoteService.java, travel/src/test/java/com/zerobase/travel/controller/VoteControllerTest.java, travel/src/test/java/com/zerobase/travel/service/VoteServiceTest.java
#12 
**AS-IS**
**TO-BE**
- 투표 기능 개발
- 테스트 코드 작성
=> feat : 투표 기능 개발

travel/src/test/java/com/zerobase/travel/controller/VoteControllerTest.java
#41 
**AS-IS**
**TO-BE**
- getVotingStart 조회 api 테스트 작성
=> test : getVotingStart 조회 api 테스트 작성

travel/src/main/java/com/zerobase/travel/common/response/ResponseMessage.java, travel/src/main/java/com/zerobase/travel/exception/BaseException.java, travel/src/main/java/com/zerobase/travel/exception/BizException.java, travel/src/main/java/com/zerobase/travel/exception/TokenException.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/BasicErrorCode.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/ErrorCode.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/Errors.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/ValidErrorCode.java, travel/src/main/java/com/zerobase/travel/handler/GlobalExceptionHandler.java
#9 
**AS-IS**
**TO-BE**
- global exception
- errorCode 추가
- exception 추가
=> feat : global exception 및 errorCode 처리

travel/src/main/java/com/zerobase/travel/controller/FileController.java, travel/src/main/java/com/zerobase/travel/controller/RatingController.java, travel/src/main/java/com/zerobase/travel/controller/ReportingController.java, travel/src/main/java/com/zerobase/travel/controller/VoteController.java, travel/src/main/java/com/zerobase/travel/entity/ReportingEntity.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/RatingErrorCode.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/ReportingErrorCode.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/VoteErrorCode.java, travel/src/main/java/com/zerobase/travel/repository/RatingRepository.java, travel/src/main/java/com/zerobase/travel/repository/ReportingRepository.java, travel/src/main/java/com/zerobase/travel/repository/VotingRepository.java, travel/src/main/java/com/zerobase/travel/repository/VotingStartRepository.java, travel/src/main/java/com/zerobase/travel/service/RatingService.java, travel/src/main/java/com/zerobase/travel/service/ReportingService.java, travel/src/main/java/com/zerobase/travel/service/VoteService.java, travel/src/test/java/com/zerobase/travel/controller/RatingControllerTest.java, travel/src/test/java/com/zerobase/travel/controller/ReportingControllerTest.java, travel/src/test/java/com/zerobase/travel/controller/VoteControllerTest.java, travel/src/test/java/com/zerobase/travel/service/RatingServiceTest.java, travel/src/test/java/com/zerobase/travel/service/ReportingServiceTest.java, travel/src/test/java/com/zerobase/travel/service/VoteServiceTest.java
**AS-IS**
**TO-BE**
- 공통 Response 응답으로 수정
- 공통 response에 맞추어 테스트 수정
- 공통 에러처리 추가
- 공통 에러처리 추가로 테스트 코드 추가
- 테스트 코드
- 투표 개시 실패
- 이미 존재하는 투표 개시
- 투표 실패
- 이미 존재하는 투표
- 유저 신고 실패
- 이미 평점을 주었음
- 평점 주기 실패
- 이미 평점을 주었음
- 평점 범위가 다름
- 평점 단위가 다름
=> feat : 공통 코드 적용

travel/src/main/java/com/zerobase/travel/common/response/Errors.java, travel/src/main/java/com/zerobase/travel/common/response/ResponseMessage.java, travel/src/main/java/com/zerobase/travel/handler/GlobalExceptionHandler.java
**AS-IS**
Errors 클래스
com.zerobase.travel.exception.errorcode 패키지에서
**TO-BE**
com.zerobase.travel.common.response 로 변경
=> refactor : 패키지 변경

user/src/main/java/com/zerobase/user/controller/UserController.java, user/src/main/java/com/zerobase/user/dto/request/EditUserInfoDTO.java, user/src/main/java/com/zerobase/user/dto/request/EditUserPasswordDTO.java, user/src/main/java/com/zerobase/user/dto/request/ProfileRequestDTO.java, user/src/main/java/com/zerobase/user/dto/response/BasicErrorCode.java, user/src/main/java/com/zerobase/user/dto/response/ErrorCode.java, user/src/main/java/com/zerobase/user/dto/response/OtherUserInfoResponseDTO.java, user/src/main/java/com/zerobase/user/dto/response/ProfileErrorCode.java, user/src/main/java/com/zerobase/user/dto/response/UserErrorCode.java, user/src/main/java/com/zerobase/user/dto/response/UserInfoResponseDTO.java, user/src/main/java/com/zerobase/user/dto/response/ValidErrorCode.java, user/src/main/java/com/zerobase/user/handler/GlobalExceptionHandler.java, user/src/main/java/com/zerobase/user/jwt/CustomLogoutFilter.java, user/src/main/java/com/zerobase/user/service/JoinService.java, user/src/main/java/com/zerobase/user/service/ProfileService.java
**TO-BE**
회원정보 수정, 회원 비밀번호 정보 수정, 다른사람 회원정보 조회, 회원정보 조회, 로그인 기능쪽 토큰관련 기능 추가
=> 회원정보 수정, 회원 비밀번호 정보 수정, 다른사람 회원정보 조회, 회원정보 조회, 로그인 기능쪽 토큰관련 기능 추가

user/build.gradle, user/src/main/java/com/zerobase/user/controller/UserController.java, user/src/main/java/com/zerobase/user/dto/request/EmailVerificationDTO.java, user/src/main/java/com/zerobase/user/dto/request/ResetPasswordEmailDTO.java, user/src/main/java/com/zerobase/user/dto/request/UserEmailAuthenticationDTO.java, user/src/main/java/com/zerobase/user/dto/response/BasicErrorCode.java, user/src/main/java/com/zerobase/user/dto/response/ValidErrorCode.java, user/src/main/java/com/zerobase/user/entity/EmailVerificationEntity.java, user/src/main/java/com/zerobase/user/repository/EmailVerificationRepository.java, user/src/main/java/com/zerobase/user/service/EmailService.java, user/src/main/java/com/zerobase/user/service/PasswordResetService.java, user/src/main/java/com/zerobase/user/service/UserService.java, user/src/main/resources/application.yml
**TO-BE**
회원 비밀번호 초기화, 회원 이메일 변경, 회원 이메일 검증
=> 회원 비밀번호 초기화, 회원 이메일 변경, 회원 이메일 검증

eureka/build.gradle, eureka/src/main/java/com/zerobase/eureka/EurekaApplication.java, eureka/src/main/resources/application.yml, gateway/build.gradle, gateway/src/main/java/com/zerobase/gateway/ApiGateWayApplication.java, gateway/src/main/resources/application.yml, settings.gradle, travel/build.gradle, travel/src/main/resources/application.yml, user/build.gradle, user/src/main/resources/application.yml
**AS-IS**
**TO-BE**
feat : api gateway 설정 및 eureka 서버 설정
=> feat : api gateway 설정 및 eureka 서버 설정

gateway/build.gradle, gateway/src/main/resources/application.yml, travel/build.gradle, travel/src/main/resources/application.yml, user/build.gradle, user/src/main/resources/application.yml
**AS-IS**
**TO-BE**
chore : eureka 현재 미사용으로 주석 처리
=> chore : eureka 현재 미사용으로 주석 처리

travel/build.gradle
=> build.gradle 수정

gateway/src/main/java/com/zerobase/gateway/config/SecurityConfig.java, travel/build.gradle, travel/src/main/java/com/zerobase/travel/post/entity/DayDetailEntity.java, travel/src/main/java/com/zerobase/travel/post/entity/DayEntity.java, travel/src/main/java/com/zerobase/travel/post/entity/ItineraryVisitEntity.java, travel/src/main/java/com/zerobase/travel/post/entity/PostEntity.java, travel/src/main/java/com/zerobase/travel/post/repository/DayDetailRepository.java, travel/src/main/java/com/zerobase/travel/post/repository/ItineraryVisitRepository.java, travel/src/main/java/com/zerobase/travel/post/repository/PostRepository.java, travel/src/main/java/com/zerobase/travel/post/type/LimitSex.java, travel/src/main/java/com/zerobase/travel/post/type/LimitSmoke.java, travel/src/main/java/com/zerobase/travel/post/type/PostStatus.java
**TO-BE**
postEntity, postRepository 추가
=> postEntity, postRepository 추가

Dockerfile_gateway, Dockerfile_travel, Dockerfile_user
- 배포시에 docker 를 통하여 배포
- gateway, user, travel 모듈에 대한 Dockerfile 작성
- 없음
=> chore : docker 배포를 위한 dockerfile 작성

travel/build.gradle
- org.hibernate:hibernate-spatial:
5.4.32.Final 버전은 현재 오류 발생
- 오류 내용은 상세하게 모르나 Spring, mysql, hibernate 등 버전 이슈가 발생한것으로 예상
- 5.4.32.Final -> 6.6.1.Final 버전으로 변경
=> chore : dependency 버전 수정

travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/dto/request/DayDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/request/DayDetailDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/request/ItineraryVisitDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/request/PostDTO.java, travel/src/main/java/com/zerobase/travel/post/entity/DayEntity.java, travel/src/main/java/com/zerobase/travel/post/entity/PostEntity.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java
=> 여행 게시판 postcreate 기능

travel/src/main/resources-local/application.yml, user/src/main/java/com/zerobase/user/config/SecurityConfig.java, user/src/main/java/com/zerobase/user/controller/InternalUserController.java, user/src/main/java/com/zerobase/user/service/UserService.java, user/src/main/resources-local/application.yml
gateway 모듈에서 restTemplate 사용해서 user 정보 가져올 interal user service 추가
없음
=> gateway 모듈에서 restTemplate 사용해서 user 정보 가져올 interal user service 추가

pay/src/main/java/com/zerobase/PaySpringMain.java, pay/src/main/java/com/zerobase/controller/PayController.java, pay/src/main/java/com/zerobase/entity/PaymentEntity.java, pay/src/main/java/com/zerobase/repository/PaymentRepository.java
복수의 Pr을 진행하기 위해서 Stacked PR 형태로 진행중이니 양해부탁드립니다.
chore) 오타 및 명칭수정
=> chore) 오타 및 명칭수정

travel/src/main/java/com/zerobase/travel/exception/errorcode/BasicErrorCode.java, travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/dto/request/PostDTO.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java, travel/src/main/resources-local/application.yml
=> post update, delete 기능 추가

travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/dto/request/DayDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/request/DayDetailDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/request/ItineraryVisitDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostDTO.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java
=> post 게시물 조회

travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/dto/request/PostSearchCriteria.java, travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostsDTO.java, travel/src/main/java/com/zerobase/travel/post/repository/PostRepository.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java, travel/src/main/java/com/zerobase/travel/post/specification/PostSpecification.java, travel/src/main/java/com/zerobase/travel/post/type/MBTI.java, travel/src/main/resources-local/application.yml
=> get post list

travel/src/main/java/com/zerobase/travel/controller/ReviewController.java, travel/src/main/java/com/zerobase/travel/dto/request/ReviewRequestDto.java, travel/src/main/java/com/zerobase/travel/entity/ReviewEntity.java, travel/src/main/java/com/zerobase/travel/entity/ReviewFileEntity.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/ReviewErrorCode.java, travel/src/main/java/com/zerobase/travel/repository/ReviewFileRepository.java, travel/src/main/java/com/zerobase/travel/repository/ReviewRepository.java, travel/src/main/java/com/zerobase/travel/service/ReviewService.java, travel/src/test/java/com/zerobase/travel/controller/ReviewControllerTest.java, travel/src/test/java/com/zerobase/travel/service/ReviewServiceTest.java
후기 작성 기능 개발
후기 작성을 위한 controller, service, repository, errorCode, entity를 정의하고
테스트 를 작성하였습니다.
없음
- create review controller 테스트 코드 작성
후기 작성시 response 값이 result : success 면 성공이다.
- create review service 테스트 코드 작성
- 성공 케이스
성공시 agumentCaptor에 저장되어있는 값이 assertEquals 값하고 동일하면 성공
- 실패 케이스
이미 존재하는 후기일경우 실패  when절의 return 값이 true 일 경우
=> feat : 후기 작성 기능 개발

travel/src/main/java/com/zerobase/travel/controller/ReviewController.java, travel/src/main/java/com/zerobase/travel/dto/request/ReviewRequestDto.java, travel/src/main/java/com/zerobase/travel/entity/ReviewEntity.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/ReviewErrorCode.java, travel/src/main/java/com/zerobase/travel/repository/ReviewRepository.java, travel/src/main/java/com/zerobase/travel/service/ReviewService.java, travel/src/test/java/com/zerobase/travel/controller/ReviewControllerTest.java, travel/src/test/java/com/zerobase/travel/service/ReviewServiceTest.java
후기 수정 기능 개발
request 받은 것을 기반으로 review 내용을 변경한다.
- error Code 수정
- 후기 수정 controller 테스트
- 성공
- 성공시 result : success 면 성공
- 후기 수정 service 테스트
- 성공
- review에 작성할 내용과 save 시 captor의 값이 같으면 성공
- 실패
- 후기 수정 실패 - 내가 작성한 후기가 아님
reviewRepository.existsByIdAndUserId() -> false 시 실패
- 후기 수정 실패 - 수정하는 후기가 postId에 해당하는 후기가 아님
reviewRepository.existsByIdAndPostId() -> false 시 실패
=> feat : 후기 수정 기능 개발

user/src/main/java/com/zerobase/user/dto/response/OtherUserInfoResponseDTO.java, user/src/main/java/com/zerobase/user/service/UserService.java
=> 다른 사용자 프로필정보 조회 업데이트

user/src/main/java/com/zerobase/user/controller/InternalUserController.java, user/src/main/java/com/zerobase/user/dto/request/UserProfileAvgRating.java, user/src/main/java/com/zerobase/user/service/UserService.java
=> 사용자 프로필 평균평점 업데이트

travel/src/main/java/com/zerobase/travel/controller/ReviewController.java, travel/src/main/java/com/zerobase/travel/service/ReviewService.java, travel/src/test/java/com/zerobase/travel/controller/ReviewControllerTest.java, travel/src/test/java/com/zerobase/travel/service/ReviewServiceTest.java
후기 삭제 기능 개발
후기를 삭제한다.
없음
- 후기 삭제 controller 테스트
- 성공
- 성공시 result : success 면 성공
- 후기 삭제 service 테스트
- 성공
- reviewId와 delete 시 captor의 값이 같으면 성공
- 실패
- 후기 삭제 실패 - 내가 작성한 후기가 아님
reviewRepository.existsByIdAndUserId() -> false 시 실패
- 후기 삭제 실패 - 수정하는 후기가 postId에 해당하는 후기가 아님
reviewRepository.existsByIdAndPostId() -> false 시 실패
=> feat : 후기 삭제 기능 개발

travel/src/main/java/com/zerobase/travel/post/dto/response/PagedResponseDTO.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java
=> 여행 게시물 조회 페이징처리

travel/src/main/java/com/zerobase/travel/post/controller/PostController.java
=> postController 수정

travel/src/main/java/com/zerobase/travel/controller/ReviewController.java, travel/src/main/java/com/zerobase/travel/dto/response/ReviewResponseDto.java, travel/src/main/java/com/zerobase/travel/repository/ReviewRepository.java, travel/src/main/java/com/zerobase/travel/repository/specification/ReviewSearchDto.java, travel/src/main/java/com/zerobase/travel/repository/specification/ReviewSpecification.java, travel/src/main/java/com/zerobase/travel/service/ReviewService.java, travel/src/test/java/com/zerobase/travel/controller/ReviewControllerTest.java, travel/src/test/java/com/zerobase/travel/service/ReviewServiceTest.java
후기 다건 조회 기능 개발
후기 다건 조회 기능 개발
- ReviewRepository에 JpaSpecificationExecutor 인터페이스 extends
- ReviewSpecification 클래스로 Review 목록 검색 필터 작성
- 후기 다건 조회 controller 테스트
- 성공
- mock 데이터와 expect 데이터가 동일하면 성공
- 후기 다건 조회 service 테스트
- 성공
- mock 데이터와 검증 데이터가 동일하면 성공
=> feat : 후기 다건 조회 기능 개발

travel/src/main/java/com/zerobase/travel/post/entity/UserClient.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java, travel/src/main/java/com/zerobase/travel/post/service/UserClientService.java, user/src/main/java/com/zerobase/user/controller/InternalUserController.java
FeignClient 응답코드 수정
각 서비스 모듈에서 FeignClient로 사용자 정보 받을때 ResponseMessage로 한번 감싸진 형태로 바뀜.
data에서 사용자 정보를 한번더 뽑아줘야함!
없음!
=> FeignClient 응답코드 수정

travel/src/main/java/com/zerobase/travel/service/ReviewService.java, travel/src/test/java/com/zerobase/travel/service/ReviewServiceTest.java
리뷰 userClient -> userClientService 로 변경
userClient에서 userClientService로 변경됨에 따라
테스트 코드와 프로덕션코드 수정
=> refactor : 리뷰 userClient -> userClientService 로 변경

user/src/test/java/com/zerobase/user/controller/UserControllerTest.java
회원가입 기능의 안정성과 신뢰성을 높이기 위해 `UserController`의 회원가입 관련 테스트 코드를 작성하였습니다. 이를 통해 다양한 입력 시나리오에서 예상한 대로 동작하는지 검증할 수 있습니다.
- `UserControllerTest` 클래스 추가 및 설정
- 회원가입 성공 시나리오 테스트 추가
- 잘못된 이메일 형식 입력 시나리오 테스트 추가
- 이미 존재하는 이메일로 회원가입 시도 시나리오 테스트 추가
- MockMvc를 활용한 통합 테스트 설정 및 MockBean을 통한 서비스 계층 모킹
- `joinProcessTest_Success`: 정상적인 회원가입 요청에 대한 성공 응답 검증
- `joinProcessTest_InvalidEmail`: 잘못된 이메일 형식 입력 시 `BadRequest` 응답 검증
- `joinProcessTest_EmailAlreadyExists`: 이미 존재하는 이메일로 인한 `Conflict` 응답 검증
- 각 테스트 케이스별로 `userService.joinProcess` 호출 여부 검증
- `MockMvc`를 활용하여 API 엔드포인트 `/api/v1/users`에 대한 POST 요청 시나리오 테스트
- CSRF 토큰을 포함한 요청으로 보안 설정 검증
- JSON 요청 및 응답의 구조와 내용을 검증 (`jsonPath` 활용)
- 향후 회원가입 외 다른 사용자 관련 기능들에 대한 테스트 코드 추가 예정
- 예외 처리 로직에 대한 상세 테스트 케이스 보강 필요
=> 회원가입 컨트롤러 테스트

user/build.gradle, user/src/main/java/com/zerobase/user/Main.java, user/src/main/java/com/zerobase/user/dto/response/OtherUserInfoResponseDTO.java, user/src/main/java/com/zerobase/user/feignclient/TravelClient.java, user/src/main/java/com/zerobase/user/service/UserParticipationService.java, user/src/main/java/com/zerobase/user/service/UserService.java, user/src/main/resources-local/application.yml
사용자 프로필에 여행횟수 필드 추가
yml 파일쪽 FeignClient 사용시 서비스 모듈 라우팅 포트번호 기재 필요해서 추가변경함.
=> 사용자 프로필에 여행횟수 필드 추가

travel/src/main/java/com/zerobase/travel/post/dto/request/PostDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostDTO.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java
여행참여 게시글쪽 선호 유형 기준이 애매하여 필드에서 삭제.
없음.
=> 선호유형 기준이 애매해서 제거

travel/src/main/java/com/zerobase/travel/exception/errorcode/BasicErrorCode.java, travel/src/main/java/com/zerobase/travel/post/constants/RepresentativeCountries.java, travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/dto/request/PostSearchCriteria.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java, travel/src/main/java/com/zerobase/travel/post/specification/PostSpecification.java
게시물 검색 필터링, 대표국가 설정 및 대표국가 검색, 비대표국가 기타로 검색 할 수 있게 설정
없음.
=> 국가 대표국가 검색, 비대표국가 기타로 검색 필터링 수정

travel/src/main/java/com/zerobase/travel/post/entity/PostEntity.java, travel/src/main/java/com/zerobase/travel/post/entity/UserClient.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java, travel/src/main/java/com/zerobase/travel/post/service/UserClientService.java, user/src/main/java/com/zerobase/user/controller/InternalUserController.java
여행 게시물 리스트 조회시 MBTI 검색 필터링을 위한 작업
검색 필터링에 mbti 기능 추가
없음
=> 여행 게시물 리스트 조회시 MBTI 검색 필터링을 위한 작업

travel/src/main/java/com/zerobase/travel/controller/ParticipationController.java, travel/src/main/java/com/zerobase/travel/dto/ParticipationDto.java, travel/src/main/java/com/zerobase/travel/dto/ParticipationsDto.java, travel/src/main/java/com/zerobase/travel/entity/ParticipationEntity.java, travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java, travel/src/main/java/com/zerobase/travel/service/ParticipationService.java
1.  controller 반환값 및 url 정정 (frontend 참여기능 사용대비)
2. managementService 로직구체화
- entity에 반환금 반환예정일추가
-  로직에 따라 반환금 반환예정일 변경로직 추가
=> WIP) Participation client 반환정보 수정, managementservice 로직 상세화

Dockerfile_pay, pay/src/main/resources-dev/application-dev.yml
docker 도입을 통한 프로그램의 환경종속성 제거
- pay 모듈의 docker file 생성
- pay 모듈의 dev 환경설정 파일 생성
=> config) pay docker img 생성을 위한 사전작업

travel/src/main/java/com/zerobase/travel/post/dto/request/PostDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostsDTO.java, travel/src/main/java/com/zerobase/travel/post/entity/PostEntity.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java
교통비, 식비를 기타경비로 통합처리
수정된 해당 필드에 맞게 서비스 코드.
=> 교통비, 식비를 기타경비로 통합처리

travel/src/main/java/com/zerobase/travel/controller/ReviewController.java, travel/src/main/java/com/zerobase/travel/repository/specification/ReviewSearchDto.java, travel/src/main/java/com/zerobase/travel/repository/specification/ReviewSpecification.java
feat : 후기 다건 조회 시 사용자ID 검색 기능 추가
Controller, ReviewSpecification, Dto에 userId 검색 부분 추가
없음
=> feat : 후기 다건 조회 시 사용자ID 검색 기능 추가

pay/build.gradle, pay/src/main/resources-dev/application-dev.yml, travel/src/main/resources-dev/application-dev.yml, travel/src/main/resources-local/application.yml, user/src/main/resources-dev/application-dev.yml
개발계 배포를 위한 설정파일 수정
pay 모듈 build.gradle 설정 수정
pay 모듈 resource 폴더를 resource-local로 수정
각 모듈의 application-dev.yml 파일 개발계 설정으로 수정
travel 모듈의 yml 의 설정 파일 오류 수정
기존 
**app**.servlet.multipart.maxFileSize
**app**.servlet.multipart.maxRequestSize
**app**.data.redis.host
**app**.data.redis.port
수정 후
**spring**.servlet.multipart.maxFileSize
**spring**.servlet.multipart.maxRequestSize
**spring**.data.redis.host
**spring**.data.redis.port
=> chore : 개발계 배포를 위한 설정파일 수정

travel/src/main/java/com/zerobase/travel/post/dto/response/UserInfoResponseDTO.java, travel/src/main/java/com/zerobase/travel/post/type/Gender.java, travel/src/main/java/com/zerobase/travel/post/type/Smoking.java, user/src/main/java/com/zerobase/user/dto/response/UserInfoResponseDTO.java, user/src/main/java/com/zerobase/user/service/UserService.java
UserInfoResponseDTO 필드 추가, 사용자 프로필 정보가 부족해서 추가함.
없음
=> UserInfoResponseDTO 업데이트

travel/src/main/java/com/zerobase/travel/exception/errorcode/VoteErrorCode.java, travel/src/main/java/com/zerobase/travel/service/RatingService.java, travel/src/main/java/com/zerobase/travel/service/ReportingService.java, travel/src/main/java/com/zerobase/travel/service/VoteService.java, travel/src/main/java/com/zerobase/travel/util/FileUtil.java, travel/src/test/java/com/zerobase/travel/service/RatingServiceTest.java, travel/src/test/java/com/zerobase/travel/service/ReportingServiceTest.java, travel/src/test/java/com/zerobase/travel/service/VoteServiceTest.java
review, report, vote의 validation을 수정하여 로직을 보강한다.
참여, 모집 게시글에 대하여 validation을 수행한다.
- error code 추가
- validation에 맞게 테스트 수정
=> feat : validation 수정

user/src/main/java/com/zerobase/user/service/ProfileService.java, user/src/main/java/com/zerobase/user/service/UserService.java
사용자 정보, 프로필 정보 수정시 Redis 캐시에도 수정사항 적용.
사용자 정보 변경사항 Redis 캐시에 저장. 
없음.
=> 사용자 정보, 프로필 정보 수정시 Redis 캐시에도 수정사항 적용.

user/src/main/java/com/zerobase/user/dto/response/OtherUserInfoResponseDTO.java, user/src/main/java/com/zerobase/user/service/UserService.java
다른사람 정보 DB에서 불러오던 것 Redis 캐시에서 가져오게 수정
다른사람 정보 Redis 캐시에서 꺼내서 보기
없음.
=> 다른사람 정보 레디스 캐시에서 꺼내서 보기

pay/build.gradle, pay/src/main/java/com/zerobase/api/ApiInterface.java, pay/src/main/java/com/zerobase/api/KakaopayApi.java, pay/src/main/resources-dev/application-dev.yml, travel/src/main/resources-dev/application-dev.yml
- pay와 travel module 통신을 위한 spring cloud 의존성 설정 (travel gradle 파일 복사함)
- dev file payservice port 정보추가
- pay 모듈 api 관련 패키지 신규생성
=> config, refactor) pay 모듈 spring cloud 의존성 설정 

travel/src/main/java/com/zerobase/travel/post/repository/PostRepository.java, travel/src/main/java/com/zerobase/travel/service/ParticipationService.java
note: 코드를 작성하다보니 PR내에 내용/코드 정리가 잘 되지 않고 PR 길이가 길어졌네요.
금일 PR 여러 건이 퀄리티가 좋지 않을 것같습니다. 최대한 정리를 좀 해보겠지만 양해부탁드립니다.
참여자가 참여를 할때 검증하는 로직 추가
**AS-IS**
참여자가 현재 참여하고 있는 여행이 2개이상인지만 확인
**TO-BE**
- 참여신청 하는 post가 존재하는지 확인 추가
- 참여신청하는 post의 참여자가 인원이 다찼는지 확인 추가
=> feat) 참여자 조건 검증 로직 추가

pay/src/main/java/com/zerobase/model/RequestPayDepositFail.java, pay/src/main/java/com/zerobase/service/DepositService.java, pay/src/main/resources-local/application.yml, travel/src/main/java/com/zerobase/travel/api/PayApi.java, travel/src/main/java/com/zerobase/travel/api/PayClient.java, travel/src/main/java/com/zerobase/travel/controller/InternalParticipationController.java, travel/src/main/java/com/zerobase/travel/controller/ParticipationController.java, travel/src/main/java/com/zerobase/travel/post/repository/PostRepository.java, travel/src/main/java/com/zerobase/travel/repository/ParticipationRepository.java, travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java, travel/src/main/java/com/zerobase/travel/service/ParticipationService.java, travel/src/main/java/com/zerobase/travel/type/DepositStatus.java, travel/src/main/java/com/zerobase/travel/type/ParticipationStatus.java
=> github merge error recovery

user/src/main/java/com/zerobase/user/dto/response/ProfileResponseDTO.java, user/src/main/java/com/zerobase/user/service/ProfileService.java
프로필 조회도 Redis 캐시 사용.
프로필 조회 DB조회에서 Redis 캐시에서 조회하도록 수정.
없음.
=> user Redis final

travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostsDTO.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java, travel/src/main/java/com/zerobase/travel/post/type/LimitSex.java, travel/src/main/java/com/zerobase/travel/post/type/LimitSmoke.java, travel/src/main/java/com/zerobase/travel/post/type/PostStatus.java
성별, 흡연유무, 게시글상태 한글로 응답
기존 영어로 내려보내주던 성별, 흡연유무, 게시글상태 한글로 응답
없음.
=> 성별, 흡연유무, 게시글상태 한글로 응답

gateway/src/main/java/com/zerobase/gateway/config/SecurityConfig.java, gateway/src/main/resources-dev/application-dev.yml, user/src/main/java/com/zerobase/user/config/SecurityConfig.java
=> logout도 routes에 포함.

travel/src/main/java/com/zerobase/travel/exception/errorcode/BasicErrorCode.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/ValidErrorCode.java, travel/src/main/java/com/zerobase/travel/handler/GlobalExceptionHandler.java, user/src/main/java/com/zerobase/user/dto/request/EditUserInfoDTO.java, user/src/main/java/com/zerobase/user/dto/request/EditUserPasswordDTO.java, user/src/main/java/com/zerobase/user/dto/request/EmailVerificationDTO.java, user/src/main/java/com/zerobase/user/dto/request/JoinDTO.java, user/src/main/java/com/zerobase/user/dto/request/ProfileRequestDTO.java, user/src/main/java/com/zerobase/user/dto/request/ResetPasswordEmailDTO.java, user/src/main/java/com/zerobase/user/dto/request/UserEmailAuthenticationDTO.java, user/src/main/java/com/zerobase/user/dto/response/BasicErrorCode.java, user/src/main/java/com/zerobase/user/dto/response/ValidErrorCode.java, user/src/test/java/com/zerobase/user/controller/UserControllerTest.java
에러코드 전체 수정 user, travel 에러코드
없음
=> 에러코드 전체 수정 user, travel 에러코드

travel/src/main/java/com/zerobase/travel/application/VotingFacade.java, travel/src/main/java/com/zerobase/travel/entity/MinusRatingEntity.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/RatingErrorCode.java, travel/src/main/java/com/zerobase/travel/repository/ParticipationRepository.java, travel/src/main/java/com/zerobase/travel/repository/RatingRepository.java, travel/src/main/java/com/zerobase/travel/repository/VotingRepository.java, travel/src/main/java/com/zerobase/travel/repository/specification/MinusRatingRepository.java, travel/src/main/java/com/zerobase/travel/service/VoteService.java
=> feat : 투표 비즈니스 로직 반영

travel/src/main/java/com/zerobase/travel/post/application/PostFacade.java, travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java
사용자 여행게시물 작성시 참여로직 추가.
여행 참여 로직에서 오류발생.
com.zerobase.travel.communities.type.CustomException: null
at com.zerobase.travel.service.ParticipationService.validateParticipationApplicant(ParticipationService.java:67) ~[main/:na]
at com.zerobase.travel.service.ParticipationManagementService.readyParticipation(ParticipationManagementService.java:55) ~[main/:na]
오류발생 합니다 상화님.
=> 사용자 여행게시물 작성시 참여로직 추가.

travel/src/main/java/com/zerobase/travel/entity/ParticipationEntity.java, travel/src/main/java/com/zerobase/travel/service/ParticipationService.java, travel/src/test/java/com/zerobase/travel/service/ParticipationManagementServiceTest.java, travel/src/test/java/com/zerobase/travel/service/ParticipationServiceTest.java
- participation test code 작성
- 검증조건 수정, 최대참여자수 관련하여 부등호 방향 변경
=> test/fix) participation test code 작성

user/src/main/java/com/zerobase/user/dto/response/BasicErrorCode.java, user/src/main/java/com/zerobase/user/jwt/LoginFilter.java, user/src/main/java/com/zerobase/user/util/ResponseUtil.java
=> 로그인 예외처리, 탈퇴한 회원, 정지당한 회원.

travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java
로그인한 사용자 userId에서 게시글 작성자 userId로 수정
없음.
=> 로그인한 사용자 userId에서 게시글 작성자 userId로 수정

travel/src/main/java/com/zerobase/travel/dto/request/GiveRatingDto.java, travel/src/main/java/com/zerobase/travel/entity/RatingEntity.java, travel/src/main/java/com/zerobase/travel/service/RatingService.java, travel/src/test/java/com/zerobase/travel/controller/RatingControllerTest.java, travel/src/test/java/com/zerobase/travel/service/RatingServiceTest.java
비즈니스 변경으로 rating entity 'comment' 컬럼 삭제
entity 및 requestDto 등 로직에서 comment 삭제
테스트코드에서 comment 관련 삭제
없음
=> feat : rating entity comment 삭제

travel/src/main/java/com/zerobase/travel/common/entity/BaseEntity.java, travel/src/main/java/com/zerobase/travel/controller/view/ReviewViewController.java, travel/src/main/java/com/zerobase/travel/dto/response/ReviewViewResponseDto.java, travel/src/main/java/com/zerobase/travel/entity/ReviewEntity.java, travel/src/main/java/com/zerobase/travel/post/entity/UserClient.java, travel/src/main/java/com/zerobase/travel/post/service/UserClientService.java, travel/src/main/java/com/zerobase/travel/service/view/ReviewViewService.java
후기 단건 조회 화면 전용 api 개발
화면 전용 API를 
ViewController, viewService를 이용하여 만듦
- BaseEntity 추가
- userClient에 userInfo를 Id로 검색하는 api 추가 (추가 개발 필요)
- userClient에 오기입되어있던 이메일 검색 메소드명 수정
updateUserRating -> getUserInfoByEmail
=> feat : review 화면 전용 api 개발

user/src/main/java/com/zerobase/user/service/UserService.java
사용자 정보, 프로필정보 Redis 캐시 이중사용 개선
사용자 정보, 프로필정보 Redis 캐시 Facade쪽에서만 캐시 사용하도록 변경.
없음.
=> Redis 캐시 이중사용 개선

pay/src/main/java/com/zerobase/config/SecurityConfig.java
pay 모듈 security config 적용
pay 모듈 security config 적용
없음
=> feat : pay 모듈 security config 적용

user/src/main/java/com/zerobase/user/controller/UserController.java
PostMapping에서 GetMapping으로 변경
없음.
=> PostMapping에서 GetMapping으로 변경

user/src/main/java/com/zerobase/user/controller/InternalUserController.java
internal 용 user 검색 api 추가
**AS-IS**
**TO-BE**
=> feat : internal 용 user 검색 api 추가

travel/src/main/java/com/zerobase/travel/exception/errorcode/VoteErrorCode.java, travel/src/main/java/com/zerobase/travel/service/VoteService.java
투표는 모집완료일때만 가능하도록 비즈니스 로직 반영
**AS-IS**
**TO-BE**
=> feat : 투표는 모집완료일때만 가능하도록 비즈니스 로직 반영

travel/src/main/java/com/zerobase/travel/application/RatingFacade.java, travel/src/main/java/com/zerobase/travel/controller/RatingController.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/RatingErrorCode.java, travel/src/main/java/com/zerobase/travel/service/RatingService.java
평점 주기 시 비즈니스 로직 반영
**AS-IS**
**TO-BE**
=> feat : 평점 주기 시 비즈니스 로직 반영

pay/src/main/java/com/zerobase/api/ApiInterface.java, pay/src/main/java/com/zerobase/api/KakaopayApi.java, pay/src/main/java/com/zerobase/api/TravelApi.java, pay/src/main/java/com/zerobase/api/TravelClient.java, pay/src/main/java/com/zerobase/controller/InternalPayController.java, pay/src/main/java/com/zerobase/service/DepositService.java, pay/src/main/java/com/zerobase/service/PayManagementService.java, pay/src/main/resources-dev/application-dev.yml, travel/src/main/java/com/zerobase/travel/controller/InternalParticipationController.java, travel/src/main/java/com/zerobase/travel/service/ParticipationService.java, travel/src/main/java/com/zerobase/travel/service/VoteService.java, travel/src/test/java/com/zerobase/travel/service/ParticipationManagementServiceTest.java
1. fix) 누락된 데이터 입력 및 메소드명으로 인한 에러 해결
1) deposit Entity 생성시 PaymentStatus 데이터 미입력
2) method명 conflict으로 인해 method 명 정정
2. refactor) FE 요청에 따른 카카오페이 redirect page 설정
3. feat) client에서 pay로 입력된 participation 정보를 participatoin 모듈에 검증로직 추가
=> Fix) 누락 데이터 입력 및 method명 conflict, feat) client의 participation 발송데이터 검증로직추가

gateway/src/main/java/com/zerobase/gateway/jwt/JwtGatewayFilterFactory.java, travel/src/main/java/com/zerobase/travel/post/application/PostFacade.java, travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/entity/PostEntity.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java
프론트와 통합테스트 중 해결해야할 문제들 수정.
**AS-IS**
게시글 등록중 게시글 PostStatus를 저장할때 MySQL에서 저장공간 부족하여 VARCHAR 저장공간을 늘려야하는 상황발생.
여행 게시물, 여행게시물 목록 조회할때 로그인 기능에서 비로그인 기능으로 수정 필요.
**TO-BE**
PostStatus MySQL에 저장시 VARCHAR(20)으로 저장되도록 수정.
여행 게시물, 여행게시물 목록 조회시 비로그인 기능으로 수정
없음.
=> 프론트와 통합테스트중 발생한 장애에 대응하기 위한 수정코드.

user/src/main/java/com/zerobase/user/application/UserInfoFacade.java, user/src/main/java/com/zerobase/user/application/UserInfoFacadeDto.java, user/src/main/java/com/zerobase/user/dto/response/OtherUserInfoResponseDTO.java, user/src/main/java/com/zerobase/user/dto/response/UserInfoResponseDTO.java, user/src/main/java/com/zerobase/user/service/UserService.java, user/src/main/java/com/zerobase/user/service/dto/UserServiceDto.java
이미지 주소도 나의 회원정보, 다른 회원정보 조회할때 조회 가능하게 수정.
없음
=> 이미지 주소도 조회 가능하게 수정.

travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, user/src/main/java/com/zerobase/user/controller/UserController.java, user/src/main/java/com/zerobase/user/dto/response/ResponseMessage.java
=> 응답 타입 리펙토링

travel/src/main/java/com/zerobase/travel/communities/controller/CommunityController.java
communities controller url error fix
기존 : /communities
변경 : /api/v1/communities
=> fix) communities url 변경

travel/src/main/java/com/zerobase/travel/controller/ParticipationController.java, travel/src/main/java/com/zerobase/travel/repository/ParticipationRepository.java, travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java, travel/src/main/java/com/zerobase/travel/service/ParticipationService.java, travel/src/main/java/com/zerobase/travel/service/ScheduleTask.java, travel/src/test/java/com/zerobase/travel/service/ParticipationManagementServiceTest.java
보증금 반환예정일 도달시 보증금 반환 하기 위한 스케쥴러 도입
- 보증금 반환시 paymodule과 kakaoapi 사용으로 transaction 및 예외처리
=> Feat) 보증금 반환 스케쥴러

travel/src/main/java/com/zerobase/travel/controller/ParticipationController.java, travel/src/main/java/com/zerobase/travel/post/repository/PostRepository.java, travel/src/main/java/com/zerobase/travel/repository/ParticipationRepository.java, travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java, travel/src/main/java/com/zerobase/travel/service/ParticipationService.java, travel/src/main/java/com/zerobase/travel/service/ScheduleTask.java, travel/src/test/java/com/zerobase/travel/service/ParticipationManagementServiceTest.java
날짜의 변화에 따라 참여의 상태를 여행완료로 변경하는 스케줄러 도입
- 여행완료로 변경전 참여상태 검증
- 해당일 + 30일 후 보증금 지급일로 설정
=> Feat) 여행일이 되면 참여상태를 변경하는 스케쥴러 도입

gateway/src/main/java/com/zerobase/gateway/jwt/JwtGatewayFilterFactory.java, travel/src/main/java/com/zerobase/travel/config/SecurityConfig.java, travel/src/main/java/com/zerobase/travel/filter/AuthenticFilter.java
travel security 적용
**AS-IS**
**TO-BE**
=> feat : travel security 적용

travel/src/main/java/com/zerobase/travel/config/SecurityConfig.java
api/v1/file 부분 permitall로 설정
**AS-IS**
**TO-BE**
=> chore : api/v1/file 부분 permitall로 설정

gateway/src/main/java/com/zerobase/gateway/config/SecurityConfig.java, user/src/main/java/com/zerobase/user/jwt/CustomLogoutFilter.java, user/src/main/java/com/zerobase/user/jwt/LoginFilter.java, user/src/main/java/com/zerobase/user/service/ReissueService.java, user/src/main/java/com/zerobase/user/util/CookieUtil.java
다른 도메인에서 로그아웃이 불가능 하던 문제 수정
**AS-IS**
**TO-BE**
=> fix : 다른 도메인에서 로그아웃이 불가능 하던 문제 수정

travel/src/main/java/com/zerobase/travel/exception/errorcode/BasicErrorCode.java, travel/src/main/java/com/zerobase/travel/post/application/PostFacade.java, travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/dto/response/createdPostResponseDTO.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java, travel/src/main/java/com/zerobase/travel/post/specification/PostSpecification.java, travel/src/main/java/com/zerobase/travel/post/type/PostStatus.java, travel/src/main/java/com/zerobase/travel/service/ParticipationService.java
모집 게시물 등록할때 게시물 상태 모집중에서 결제 대기중으로 변경.
없음.
postId와 participationId 응답으로 내려줌.
=> 모집 게시물 작성 모집중에서 결제 대기중으로 변경.

pay/src/main/java/com/zerobase/model/RequestApi.java, travel/src/main/java/com/zerobase/travel/communities/entity/CommunityEntity.java, travel/src/main/java/com/zerobase/travel/communities/service/CommunityManagementService.java, travel/src/main/java/com/zerobase/travel/communities/service/CommunityService.java, travel/src/main/java/com/zerobase/travel/communities/type/CommunityDto.java, travel/src/main/java/com/zerobase/travel/communities/type/ResponseCommunityDto.java, travel/src/test/java/com/zerobase/travel/communities/service/CommunityManagementServiceTest.java, travel/src/test/java/com/zerobase/travel/communities/service/CommunityServiceTest.java, user/src/main/resources-local/application.yml
1. FE요청에 따라 community entity내 대륙,국가,지역 정보삭제
2. community entity soft delete을 위한 status 추가 및 delete method 추가
3. response에 community 생성일 추가
그외 
4. pay api request dto 중 필요 annotaion 추가
=> Refactor/ FE 요청에 따른 communities entity 값 변경

travel/src/main/java/com/zerobase/travel/config/SecurityConfig.java
feat : travel internal Api 전체 메소드 허용
**AS-IS**
**TO-BE**
=> feat : travel internal Api 전체 메소드 허용

travel/src/main/java/com/zerobase/travel/communities/controller/CommunityController.java, travel/src/main/java/com/zerobase/travel/communities/repository/CommunityRepository.java, travel/src/main/java/com/zerobase/travel/communities/service/CommunityService.java, travel/src/main/java/com/zerobase/travel/communities/type/RequestUpdateCommunity.java, travel/src/main/java/com/zerobase/travel/exception/errorcode/CommunityErrorCode.java, travel/src/test/java/com/zerobase/travel/communities/service/CommunityServiceTest.java
1. Community 기능 fix
**AS-IS**
- Community 내 국가,지역, 대륙 항목이 정책상 제외되었음에도 해당 필드 dto validation 진행중이었음.
**TO-BE**
- Request dto 필드 제거 및  Validation 제거 ;  -> Interface로 묶으면 조금더 유지보수성이 좋겠다는 생각이 들었습니다.
그 외 URL 정정
2. Commnity 에러 공통화
=> Fix/communities 버그수정 / 에러공통화

travel/src/main/java/com/zerobase/travel/exception/errorcode/ValidErrorCode.java, travel/src/main/java/com/zerobase/travel/post/dto/request/DayDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/request/DayDetailDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/request/ItineraryVisitDTO.java, travel/src/main/java/com/zerobase/travel/post/dto/request/PostDTO.java
- 요청 데이터 검증 시 적절한 에러 메시지를 제공하지 못했던 문제 해결.
- 유효성 검사 오류 시 명확한 에러 코드와 메시지를 클라이언트에 전달하기 위한 구조 개선.
---
1. DTO에 유효성 검사 애너테이션(`@NotNull`, `@NotBlank` 등)은 있었으나, 오류 발생 시 기본 메시지만 반환.
2. 오류 코드와 메시지가 특정 요구사항에 맞지 않음.
1. 모든 DTO 필드에 구체적인 에러 코드 추가:
- `@NotNull`, `@NotBlank`, `@Future` 등과 같은 유효성 검사 애너테이션에 프로젝트의 에러 코드 체계 반영.
- 예:
```java
@NotNull(message = "ERROR-POST-00008")
private LocalDate travelStartDate;
@FutureOrPresent(message = "ERROR-POST-00009")
private LocalDate travelStartDate;
```
2. 에러 코드 관리:
- **`ValidErrorCode`** 열거형에 새로운 에러 코드를 추가하여 중앙에서 관리.
- 예:
```java
NO_TITLE_ERROR("ERROR-POST-00001", "제목은 필수입니다."),
INVALID_START_DATE_ERROR("ERROR-POST-00009", "여행 시작 날짜는 현재보다 이전일 수 없습니다.");
```
3. DTO 변경:
- `PostDTO`, `DayDTO`, `DayDetailDTO`, `ItineraryVisitDTO` 등에 적절한 유효성 검사 애너테이션 및 에러 코드 추가.
4. 전역 …
=> 모집 게시글 등록시 필수값 여부 체크.

travel/src/main/java/com/zerobase/travel/service/RatingService.java
feat : validation 수정 participation status
**AS-IS**
**TO-BE**
=> feat : validation 수정 participation status

pay/src/main/java/com/zerobase/service/PayManagementService.java, travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java
DB 자원 경쟁 최소화를 위한 Transactional 적용범위 최소화
- Fail fast 구조를 통해 Transactional 제거
- Transactional이 필수적인 작업의 경우 별도의 TrsnactionService를 통해 작업하여 적용범위 최소화
=> Refactor/ transactional 사용최소화를 위한 코드수정

user/src/main/java/com/zerobase/user/dto/response/OtherUserInfoResponseDTO.java
=> 다른회원정보 조회시 추가적인 데이터 조회.

user/src/main/java/com/zerobase/user/service/ReissueService.java
reissue시 accessToken 시간 10분에서 30분으로 수정.
=> reissue시 accessToken시간 10분에서 30분으로 변경

travel/src/main/java/com/zerobase/travel/typeCommon/Continent.java
=> Feature continent fix

travel/src/main/java/com/zerobase/travel/post/controller/PostController.java, travel/src/main/java/com/zerobase/travel/post/dto/request/PostSearchCriteria.java, travel/src/main/java/com/zerobase/travel/post/service/PostService.java, travel/src/main/java/com/zerobase/travel/post/specification/PostSpecification.java
=> 모집게시글 필터링 region 추가
