- pay/src/main/java/com/zerobase/model/DepositDto.java
- pay/src/main/java/com/zerobase/model/PayReadyApiDto.java
- pay/src/main/java/com/zerobase/model/RequestApi.java
- pay/src/main/java/com/zerobase/model/RequestConfirmPayDeposit.java
- pay/src/main/java/com/zerobase/model/RequestReadyPayDeposit.java
- pay/src/main/java/com/zerobase/model/ResponseApi.java
- pay/src/main/java/com/zerobase/model/ResponseDepositPayDto.java
- pay/src/main/java/com/zerobase/model/exception/CustomException.java
- pay/src/main/java/com/zerobase/model/type/PaymentDto.java
- 메소드별 DTO 도입을 통해서 계층간의 데이터 이동을 유연화 및 명확화 하고자함
**AS-IS**
계층별 dto 최초생성
**TO-BE**
- Controller 측에서 client의 request와 response에 대한 정의하여 최종적으로 client가 payready 상태의 kakao api url을 받게하고자함
- Service layer 간의 개별 dto 도입함
그 외 customexception 형상생성 
결제준비 외의 controller request dto 생성, 기획세부사항 결정시 적용예정
테스트 해당사항 없음
> Feat/pay controller 및 계층별 dto 생성

- travel/src/main/java/com/zerobase/travel/exception/errorcode/VoteErrorCode.java
- travel/src/main/java/com/zerobase/travel/post/repository/PostRepository.java
- travel/src/main/java/com/zerobase/travel/repository/VotingStartRepository.java
- travel/src/main/java/com/zerobase/travel/service/VoteService.java
- travel/src/test/java/com/zerobase/travel/service/VoteServiceTest.java
vote 기능에 validation을 보완하여 비즈니스에 알맞게 한다.
- 투표 시작시 모집글 작성자만 가능하도록 validation한다.
- 투표 시 게시글ID에 맞는 투표ID인지 확인하여 다른 투표, 다른 게시글에 투표하지 못하도록 validation한다.
없음
- createVote 시 post table에 postId, userId에 해당하는 로우가 없으면 
BizException(VoteErrorCode.ONLY_AUTHOR_CAN_START_VOTE) 
- voteVoting 시 votingStart 테이블에 votingStartId, postId에 해당하는 로우가 없으면
BizException(VoteErrorCode.VOTE_NOT_ALLOW_THIS_POST)
> feat : vote validation 보강

- gateway/src/main/java/com/zerobase/gateway/jwt/JwtGatewayFilterFactory.java
- gateway/src/main/java/com/zerobase/gateway/util/JWTUtil.java
- user/src/main/java/com/zerobase/user/dto/response/BasicErrorCode.java
- user/src/main/java/com/zerobase/user/jwt/LoginFilter.java
- user/src/main/java/com/zerobase/user/service/ReissueService.java
- user/src/main/java/com/zerobase/user/util/JWTUtil.java
기존 apigateway에서 토큰을 통해 사용자 email을 헤더에서 꺼내서 user 모듈쪽으로 feignClient써서 사용자 정보를 가져오는 구조에서
애초에 토큰에 uesrId 넣어두면 userId만 필요한 컨트롤러에서 feignClient로 사용자 정보를 user모듈쪽에서 가져올 필요가 없음.
jwt 토큰에 userId 필드 추가, apigateway에서 userId를 헤더에 포함시켜 넘겨주기 위함
> jwt 토큰에 userId 필드 추가, apigateway에서 userId를 헤더에 포함시켜 넘겨주기 위함

- pay/src/main/java/com/zerobase/controller/PayController.java
- pay/src/main/java/com/zerobase/entity/DepositEntity.java
- pay/src/main/java/com/zerobase/entity/PaymentEntity.java
- pay/src/main/java/com/zerobase/model/DepositDto.java
- pay/src/main/java/com/zerobase/model/RequestApi.java
- pay/src/main/java/com/zerobase/model/ResponseDepositPayDto.java
- pay/src/main/java/com/zerobase/model/ResponsePaymentDto.java
- pay/src/main/java/com/zerobase/model/type/DepositStatus.java
- pay/src/main/java/com/zerobase/model/type/PaymentDto.java
- pay/src/main/java/com/zerobase/repository/PaymentRepository.java
- pay/src/main/java/com/zerobase/service/DepositService.java
- pay/src/main/java/com/zerobase/service/KakaopayApiService.java
- pay/src/main/java/com/zerobase/service/PayManagementService.java
- pay/src/main/java/com/zerobase/service/PaymentService.java
- pay/src/test/resources/payAPITest.http
비즈니스 기획 구체화로 인해서 Deposit의 status 관리가 필요 없어짐
-> deposit 객체 생성시점과 결제완료 시점이 동일해짐
-> deposit은 주문의 개념이므로 deposit의 반환여부는 participation객체 에서 관리
Payservice의 결제내역조회, 결제확정기능 등 신규도입과 코드 일부수정
**AS-IS**
1. Deposit의 생성후 결제이전, 결제완료, 환불완료로 관리함
**TO-BE**
1. Deposit생성시점과 결제시점이 동일한 트랜잭션으로 처리하기로 결정되어 Desposit의 status 값 삭제
2. PayService 결제확정기능 도입
3. PayService 결제내역조회
결제준비, 결제내역확인, 결제확정처리 기능 동작확인
> feat) payservice deposit entity 변경 및 서비스 결제확정, 취소 기능 추가

- travel/src/main/java/com/zerobase/travel/controller/ReviewController.java
- travel/src/main/java/com/zerobase/travel/dto/response/ReviewResponseDto.java
- travel/src/main/java/com/zerobase/travel/entity/ReviewEntity.java
- travel/src/main/java/com/zerobase/travel/exception/errorcode/ReviewErrorCode.java
- travel/src/main/java/com/zerobase/travel/service/ReviewService.java
- travel/src/test/java/com/zerobase/travel/controller/ReviewControllerTest.java
- travel/src/test/java/com/zerobase/travel/service/ReviewServiceTest.java
후기 단건 조회 기능 개발
- 후기 단건 조회 기능 개발
- ReviewEntity fetchType.EAGER 로변경
review 가져올때 대부분 file정보도 필요할것으로 예상되어 EAGER로 변경
- ErrorCode 의 message 내용 수정
- 후기 단건 조회 controller 테스트
- 성공
- 성공시 result : success 이고 return value 가 given 절과 동일하면 성공
- 후기  단건 조회 service 테스트
- 성공
- 조회 시 given ReviewEntity의 값과 return Dto의 값이 동일하면 성공
- 실패
- 후기 단건 조회 실패 - 후기 없음
reviewRepository.findById(anyLong()) -> optional empty 시 실패
- 후기 단건 조회 실패 - 조회한 후기가 해당 모집글의 후기가 아님
reviewRepository.existsByIdAndPostId(anyLong(), anyLong()) -> false 시 실패
> feat : 후기 단건 조회 기능 개발

- travel/src/main/java/com/zerobase/travel/api/UserApi.java
- travel/src/main/java/com/zerobase/travel/api/UserApiRequestDto.java
- travel/src/main/java/com/zerobase/travel/controller/RatingController.java
- travel/src/main/java/com/zerobase/travel/post/entity/UserClient.java
- travel/src/main/java/com/zerobase/travel/post/service/UserClientService.java
- travel/src/main/java/com/zerobase/travel/repository/RatingRepository.java
- travel/src/main/java/com/zerobase/travel/service/RatingService.java
- travel/src/test/java/com/zerobase/travel/controller/RatingControllerTest.java
- travel/src/test/java/com/zerobase/travel/service/RatingServiceTest.java
사용자에게 평점을 줄 시 평점을 받은 사용자의 profile의 평균 평점을 update 해준다.
**AS-IS**
기존에는 user profile update를 하지 않고 평점 테이블에만 저장을함
**TO-BE**
user profile을 평균 평점으로 update를 해줌
- 평균 평점은 소숫점 한자리를 기준으로 올림처리함.
- 로직 수정이 되어 테스트 코드 수정
- UserClient 부분에 updateUserRating 추가
- JPQL을 통한 평균 구하는 메소드 추가
기존 success 테스트 로직에 userApi mock 처리하였음
현재는 RatingService에 사용자 프로필 평점 update 부분을 넣어주었지만
Facade 패턴을 도입해 facade 클래스에
{
ratingservice.giveRating(...);
userApi.updateUserRating(...);
}
방식으로 작성하게된다면 메소드만으로 어떤 기능인지 빠르게 확인할 수 있고
테스트의 수정이 없었을 것으로 생각한다.
> feat : 평점 주기 기능 로직 수정

- travel/src/main/java/com/zerobase/travel/controller/ReportingController.java
- travel/src/main/java/com/zerobase/travel/controller/VoteController.java
- travel/src/test/java/com/zerobase/travel/controller/ReportingControllerTest.java
- travel/src/test/java/com/zerobase/travel/controller/VoteControllerTest.java
임시로 userId를 고정시켜 놓았던 것을 header를 통해 userId를 받도록 변경
**AS-IS**
메소드 내부에서 long userId = 1L; 로 고정되어있었음.
**TO-BE**
header를 통해 userId를 받아오도록 변경
- header 방식으로 가져올수 있게 테스트 코드를 수정함
- spring security 적용으로인해 테스트가 fail나오는 상황을 csrf와 mockUser 설정으로 해결
> refactor : userId를 header를 통해 가져오도록 변경

- travel/build.gradle
- travel/src/main/java/com/zerobase/travel/post/config/KafkaConsumerConfig.java
- travel/src/main/java/com/zerobase/travel/post/entity/PostEntity.java
- travel/src/main/java/com/zerobase/travel/post/kafka/UserMbtiChangedEvent.java
- travel/src/main/java/com/zerobase/travel/post/repository/PostRepository.java
- travel/src/main/java/com/zerobase/travel/post/service/PostService.java
- travel/src/main/java/com/zerobase/travel/post/service/UserMbtiChangedEventListener.java
- travel/src/main/resources-local/application.yml
- user/build.gradle
- user/src/main/java/com/zerobase/user/config/KafkaProducerConfig.java
- user/src/main/java/com/zerobase/user/kafka/UserMbtiChangedEvent.java
- user/src/main/java/com/zerobase/user/service/ProfileService.java
- user/src/main/resources-local/application.yml
🔍 **PR을 통해 해결하려는 문제**
- **사용자 MBTI 정보 동기화 문제**: 사용자가 자신의 MBTI를 수정할 경우, `travel` 모듈에서 해당 사용자가 작성한 모든 여행 게시물의 MBTI 정보가 자동으로 업데이트되지 않는 문제가 있었습니다. 이는 사용자 프로필과 게시물 사이의 MBTI 정보 불일치로 이어져 사용자 경험을 저해할 수 있습니다.
🔑 **PR에서 핵심적으로 변경된 사항**
1. **Kafka를 이용한 이벤트 기반 아키텍처 구현**
- **이벤트 발행 (`user` 모듈)**:
- 사용자의 MBTI가 변경될 때 `UserMbtiChangedEvent` 이벤트를 Kafka 토픽으로 발행하도록 구현했습니다.
- `ProfileService`에 MBTI 변경 시 이벤트를 발행하는 로직을 추가했습니다.
- **이벤트 수신 (`travel` 모듈)**:
- `UserMbtiChangedEventListener`를 생성하여 Kafka 토픽으로부터 이벤트를 수신합니다.
- 수신된 이벤트를 기반으로 해당 사용자의 모든 게시물의 MBTI 정보를 업데이트합니다.
2. **Kafka 설정 추가 및 수정**
- **의존성 추가 (`build.gradle`)**:
- `org.springframework.kafka:spring-kafka` 라이브러리를 추가하여 Kafka를 활용할 수 있도록 했습니다.
- 테스트를 위한 `spring-kafka-test` 의존성을 추가했습니다.
- **설정 파일 수정 (`application.yml`)**:
- Kafka 서버 주소 및 기본 설정을 추가했습니다.
- 이벤트 …
> 사용자 MBTI 수정시, travel 모듈쪽 해당 작성자의 모든 여행 게시물 MBTI 내용도 이벤트 발생시 수정.

- travel/src/main/java/com/zerobase/travel/post/service/PostService.java
- travel/src/main/java/com/zerobase/travel/post/specification/PostSpecification.java
여행 게시물 목록 보여줄때 삭제된것과 모집마감글은 제외하고 보여줌.
게시물 전체 보여줌 ->  삭제된것과 모집마감글은 제외하고 보여줌.
없음
> 여행 게시물 목록 보여줄때 삭제된것과 모집마감글은 제외하고 보여줌.

- pay/src/main/java/com/zerobase/service/DepositService.java
- travel/src/main/java/com/zerobase/travel/api/PayApi.java
- travel/src/main/java/com/zerobase/travel/api/PayClient.java
- travel/src/main/java/com/zerobase/travel/controller/InternalParticipationController.java
- travel/src/main/java/com/zerobase/travel/controller/ParticipationController.java
- travel/src/main/java/com/zerobase/travel/repository/ParticipationRepository.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java
- travel/src/main/java/com/zerobase/travel/type/DepositStatus.java
- travel/src/main/java/com/zerobase/travel/type/ParticipationStatus.java
note:  코드를 작성하다보니 PR내에 내용/코드 정리가 잘 되지 않고 PR 길이가 길어졌네요. 
금일 PR 여러 건이 퀄리티가 좋지 않을 것같습니다. 최대한 정리를 좀 해보겠지만 양해부탁드립니다.
1. Transactional annotation 제거를 위한 Participation Entity 상태추가 
2. Transaction annotation 제거를 위한 메소드, 메소드 호출 구조변경
3. Pay모듈 Travel모듈 연결을 위한 payclient 생성
1. Transactional annotation 제거를 위한 Participation Entity, Deposit Entity 상태추가 
**AS-IS**
트랜잭션 처리를 통해서 결제가 완료된 경우에만 Participation, Deposit 데이터를 생성하도록 처리
-> 해당 방식은 외부 API를 호출하고 유저가 결제를 하는 동안 Transaction 처리하는 방식으로 Lock이 걸리는 기간이 매우김
**TO-BE**
결제전 단계를 도입하여 participation Join ready, deposit unpaid 상태로 우선 데이터 생성 그 후 결제를 시도하여 성공시 상태변경을 저장
->  join ready, deposit unpaid는 외부 API가 실패할 경우에만 잔류하며 예외처리로 데이터 정리하여 데이터 무결성 확보예정
2.  Transaction annotation 제거를 위한 ParticipationService 메소드, 메소드 호출 구조변경
**AS-IS**
서비스 로직을 <외부API호출+데이터상태변경 및 저장>을 트랜잭션 처리하여 …
> feat) payclient 도입 , refactor) transaction제거를 위한 로직 및 데이터 상태 세분화

- travel/src/main/java/com/zerobase/travel/post/service/PostService.java
삭제된 여행 게시물 조회할때 게시글 찾을수 없다는 에러 메시지 응답.
기존 삭제된 여행 게시물도 조회 되었지만, 삭제처리되면 게시글을 찾을 수 없다는 에러 메시지 응답으로 변경/
없음.
> 삭제된 여행 게시물 조회할때 게시글 찾을수 없다는 에러 메시지 응답.

- pay/src/main/java/com/zerobase/entity/DepositEntity.java
- pay/src/main/java/com/zerobase/entity/KakaoPayPaymentHistoryEntity.java
- pay/src/main/java/com/zerobase/entity/PaymentEntity.java
- pay/src/main/java/com/zerobase/model/exception/CustomException.java
- pay/src/main/java/com/zerobase/model/exception/ErrorCode.java
- pay/src/main/java/com/zerobase/service/DepositService.java
- pay/src/main/java/com/zerobase/service/PayManagementService.java
- pay/src/main/java/com/zerobase/service/PaymentService.java
- travel/src/main/java/com/zerobase/travel/controller/ParticipationController.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationService.java
front end와 통합 test전 문제점 hotfix
1. refactor) entity의 enum type String으로 저장
2. fix) controller userId를 x-user-id로 변경
3. refactor) validationParticipation logic을 travel모듈 error도 pay모듈 내에서 excpetion 처리하도록 변경
4. refactor) errorcode 내 메세지 상세화
> Fix) Participation controller userId 받는 방식 변경

- travel/src/main/java/com/zerobase/travel/controller/ParticipationController.java
- travel/src/main/java/com/zerobase/travel/controller/ResponseParticipationsByUserDto.java
- travel/src/main/java/com/zerobase/travel/dto/ResponseParticipationsByPostDto.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationService.java
FE 요청으로 인해, 유저가 현재 참여중인 게시글 ID조회기능추가
- Participation과 Post는 oneToMany관계로 연관관계를 통해서 PostId참조
-> 최대 참여개수가 2개인 관계로 N+1문제는 무시함.
->Participation 상태 중 Join ready와 Join 상태 모두 조회되도록 설정
기타변경사항
기존 유사한 기능의 responsedto 명칭변경을 통해 구분명확화
- [ x] API 테스트
> Feat) 유저가 현재 참여중인 게시글Id 조회기능

- pay/src/main/java/com/zerobase/model/RequestApi.java
- pay/src/main/java/com/zerobase/model/RequestConfirmPayDeposit.java
- pay/src/main/java/com/zerobase/model/RequestPayDepositFail.java
- pay/src/main/java/com/zerobase/model/RequestPayDepositSuccess.java
- pay/src/main/java/com/zerobase/model/RequestReadyPayDeposit.java
- pay/src/main/java/com/zerobase/model/RequestpayDepositRefund.java
- travel/src/main/java/com/zerobase/travel/communities/controller/CommunityController.java
- travel/src/main/java/com/zerobase/travel/communities/service/CommunityManagementService.java
- travel/src/main/java/com/zerobase/travel/communities/type/RequestCreateCommunity.java
- travel/src/main/java/com/zerobase/travel/communities/type/RequestUpdateCommunity.java
- travel/src/main/java/com/zerobase/travel/communities/type/ResponseCommunityDto.java
- travel/src/test/java/com/zerobase/travel/communities/controller/CommunityControllerTest.java
- travel/src/test/java/com/zerobase/travel/communities/service/CommunityManagementServiceTest.java
- Communities create시 file이 입력되지 않으면 nullpoint exception이 발생하던 문제 해결
- request dto에 불필요한 lombok args 제거 
-  request dto에 private 미추가 필드 추가
**AS-IS**
request의 file list field에 기본값이 없어 file save method 내에서 stream 처리시 nullpoint excpetion 발생
**TO-BE**
request의 file list field에 list 초기값 설정으로 오류해결
- [x ] API 테스트
> fix) Communities request dto field 초기값 설정으로 nullpoint exception 해결

- travel/src/main/java/com/zerobase/travel/communities/service/CommunityService.java
community delete기능시, findByuserId로 찾던 기능을 findBycommunityId로 변경
- repo에서 entity 타입으로 반환하나, db에서 검색된 레코드는 복수건으로 error발생문제해결
- [ x] API 테스트
> fix) community delete기능시, findByuserId로 찾던 기능을 findBycommunityId로 변경

- travel/src/main/java/com/zerobase/travel/post/specification/PostSpecification.java
PAYMENT_PENDING, DELETED 인 상태의 글목록만 보이게 수정.
없음
없음
> 모집 게시글 조회 조건 수정

- travel/src/main/java/com/zerobase/travel/post/service/PostService.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationService.java
1. 참여신청시 post의 상태를 검증하는 메소드 변경
**AS-IS**
참여신청 대상인 post의 상태가 RECRUITING인지 검증  
**TO-BE**
참여신청자가 작성자인경우 post의 상태 검증은 하지 않음
2. post 작성자의 결제완료시 post의 상태를 변경하는 로직 추가
**AS-IS**
결제완료시 post의  상태변경 없음
**TO-BE**
결제완료시 post의  상태 PAYMENTPENDING에서 RECRUITING으로 변경
> Feat/Post 상태 신규 도입으로 인한 participation 로직변경

- travel/src/main/java/com/zerobase/travel/entity/ParticipationEntity.java
- travel/src/main/java/com/zerobase/travel/repository/ParticipationRepository.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationScheduleTask.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationService.java
JoinReady 후 결제신청 단계까지 넘어가지 못한 데이터 정리 스케줄러 도입
**AS-IS**
사용자가 참여신청 후, 결제단계까지 연계하는 과정을 프론트의 API 호출에 의존하는 구조로
이과정에서 사용자의 비정상 동작/ 통신오류로 비정상 데이터 잔여할 수 있음
**TO-BE**
매시간 정각 24시간이 경과한 잔여데이터 정리하는 스케줄러 도입
- 비정상 케이스가 많이 발생할 것으로 예상되지는 않아 별도 페이징 처리는 하지 않음.
JPA Audit 기능 작동하도록 Participation Entity 내 Listener 추가
> Feat/ 참여데이터 비정상 데이터 정리 스케줄러 추가 

- user/src/main/java/com/zerobase/user/dto/response/OtherUserInfoResponseDTO.java
- user/src/main/java/com/zerobase/user/type/MBTI.java
다른 사람의 프로필을 조회할 때 MBTI 필드가 조회되지 않는 문제가 있었습니다. 사용자들은 다른 사용자의 MBTI 정보를 확인하고 싶어하지만, 현재 API에서는 해당 정보를 제공하지 않고 있습니다. 이를 해결하기 위해 다른 사용자 프로필 조회 시 MBTI 필드를 추가로 조회하도록 수정합니다.
**AS-IS**
- `OtherUserInfoResponseDTO` 클래스에는 `mbti` 필드가 존재하지 않아, 다른 사용자 프로필 조회 시 MBTI 정보를 제공하지 못했습니다.
- `UserInfoFacadeDto`에서 가져온 MBTI 정보를 `OtherUserInfoResponseDTO`로 매핑하지 않았습니다.
**TO-BE**
- `OtherUserInfoResponseDTO` 클래스에 `mbti` 필드를 추가하였습니다.
```java
private String mbti;
```
- `UserInfoFacadeDto`에서 가져온 MBTI 정보를 `OtherUserInfoResponseDTO`로 매핑하도록 수정하였습니다.
```java
.mbti(userInfoFacadeDto.getMbti().name())
```
- 이를 통해 다른 사용자 프로필 조회 시 MBTI 정보가 포함되어 응답되며, 사용자들은 다른 사용자의 MBTI를 확인할 수 있게 되었습니다.
- **`MBTI` Enum 클래스에 `@Getter` 어노테이션 추가**: 필요에 따라 `MBTI` Enum 클래스에 Lombok의 `@Getter` 어노테이션을 추가.
```java
@Getter
public enum MBTI {
// 기존 내용 유지
} …
```
> 다른 사람 정보 조회 시, mbti 필드 추가

- travel/src/main/java/com/zerobase/travel/post/entity/DayDetailEntity.java
- travel/src/main/java/com/zerobase/travel/post/entity/DayEntity.java
- travel/src/main/java/com/zerobase/travel/post/entity/PostEntity.java
- travel/src/main/java/com/zerobase/travel/post/service/PostService.java
게시물 상세 조회 및 게시물 목록 조회 시 데이터의 순서가 뒤바뀌어 조회되는 문제를 해결. 기존에는 데이터가 등록된 순서대로 조회되지 않고, 매번 순서가 변경되어 사용자에게 혼란을 주는 이슈가 있었습니다.
**AS-IS**
- 엔티티 클래스(`PostEntity`, `DayEntity` 등)에서 연관된 컬렉션들을 `Set`으로 정의하고 있었습니다.
- `Set`은 요소의 순서를 보장하지 않기 때문에 조회 시 데이터의 순서가 뒤바뀌는 문제가 발생했습니다.
- 게시물 상세 조회 시 `days`, `dayDetails`, `itineraryVisits` 등의 순서가 랜덤하게 나타났습니다.
**TO-BE**
- 엔티티 클래스에서 연관된 컬렉션 타입을 `Set`에서 `List`로 변경하였습니다.
```java
// 변경 전
private Set<DayEntity> days = new HashSet<>();
// 변경 후
private List<DayEntity> days = new ArrayList<>();
```
- `List`는 요소의 삽입 순서를 유지하므로, 데이터가 등록된 순서대로 조회됩니다.
- 서비스 계층에서 엔티티를 DTO로 매핑할 때, 컬렉션을 정렬하여 순서를 보장하였습니다.
```java
// 예시 코드
existingPost.getDays().stream()
.sorted(Comparator.comparingInt(existingPost.getDays()::indexOf))
.map(dayEntity -> { /* 매핑 로직 */ })
.collect(Collectors.toList());
``` …
> [HotFix] 모집게시글 상세조회시 일정순서가 랜덤으로 조회되던 문제

- travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostDTO.java
- travel/src/main/java/com/zerobase/travel/post/dto/response/ResponsePostsDTO.java
- travel/src/main/java/com/zerobase/travel/post/dto/response/UserInfoResponseDTO.java
- travel/src/main/java/com/zerobase/travel/post/entity/UserClient.java
- travel/src/main/java/com/zerobase/travel/post/service/PostService.java
- travel/src/main/java/com/zerobase/travel/post/service/UserClientService.java
- travel/src/main/java/com/zerobase/travel/post/type/MBTI.java
- user/src/main/java/com/zerobase/user/controller/InternalUserController.java
- user/src/main/java/com/zerobase/user/dto/response/InternalUserInfoResponseDTO.java
- user/src/main/java/com/zerobase/user/service/UserService.java
기존 게시글 조회 및 목록 API 응답 DTO(`ResponsePostDTO`, `ResponsePostsDTO`)에서 사용자 닉네임 및 프로필 사진과 같은 추가 사용자 정보가 표시되지 않아, UI 단에서 게시글 작성자에 대한 충분한 정보를 제공하기 어려웠습니다. 이 PR에서는 사용자 서비스를 통해 사용자 정보를 가져와 게시글 응답 DTO에 반영함으로써, 최종 클라이언트(프런트엔드)에서 추가적인 정보를 표시할 수 있도록 수정됨.
- `ResponsePostDTO`, `ResponsePostsDTO` DTO에 `nickname`, `profileFileAddress`, `mbti` 필드 추가  
- 기존 `UserClientService`에 `getUserInfoByUserId()` 메서드 추가  
- `PostService`의 `mapToDTO()` 로직에서 `UserClientService`를 호출해, 게시글 작성자의 닉네임, 프로필 파일 주소, MBTI를 DTO에 매핑  
- 상세 조회(`findPost`) 및 목록 조회(`searchPosts`) 시점에서 사용자 정보를 DTO에 포함하도록 변경
- 게시글 상세/목록 응답 DTO에 위에 3가지 사용자 정보 없음  
- `mapToDTO()` 내에서 게시글 정보만 DTO로 변환하며, 사용자 정보는 userId만 표시  
- 프런트엔드에서 별도의 호출을 통해 사용자 정보를 가져와야 하는 불편함 존재
- 게시글 상세/목록 응답 DTO에 사용자 정보(`nickname`, `profileFileAddress`, `mbti`) 포함  
- `mapToDTO()`에서 …
> 모집 게시글 목록 조회시, 작성자 MBTI 필드 추가.

- travel/src/main/java/com/zerobase/travel/application/ReviewFacade.java
- travel/src/main/java/com/zerobase/travel/application/dto/ReviewFacadeDto.java
- travel/src/main/java/com/zerobase/travel/controller/ReviewController.java
- travel/src/main/java/com/zerobase/travel/dto/response/ReviewResponseDto.java
- travel/src/main/java/com/zerobase/travel/service/ReviewService.java
- travel/src/main/java/com/zerobase/travel/service/dto/ReviewServiceDto.java
- travel/src/test/java/com/zerobase/travel/application/ReviewFacadeTest.java
- travel/src/test/java/com/zerobase/travel/controller/ReviewControllerTest.java
- travel/src/test/java/com/zerobase/travel/service/ReviewServiceTest.java
1. review 목록 response 데이터 추가
2. review 코드 구조 개선
1. review 목록 response 데이터에 review 작성자 mbti, nickname. 프로필사진경로 추가
2. Facade 도입
reviewService에 변경사항을 최소화하고 재사용성을 높이기 위하여 도입
4. 각레이어에 맞는 DTO 도입
기존 Controller에서 사용하던 Dto가 service에서도 사용되어 response가 변경됨에 따라 Service가 영향을 받았음.
위의 문제를 해결하기 위해 의존성을 controller가 service, facade를 의존하게 하여 controller에 변경에 영향을 최소화함.
1. reviewFacadeDto에 User가 생겨 SRP가 잘 지켜지지 않은 코드가 된 것 같음.
2. User에 변경이 생길 시 영향이 갈 것으로 예상이 됨.
없음
- 성공케이스만 작성.
- controller, facade, service에 맞추어 테스트 변경 및 추가.
- given에 추가한 모든 데이터를 검증.
> feat : review 목록 response 데이터 추가

- travel/src/main/java/com/zerobase/travel/post/controller/PostController.java
- travel/src/main/java/com/zerobase/travel/post/entity/DayEntity.java
- travel/src/main/java/com/zerobase/travel/post/entity/PostEntity.java
- travel/src/main/java/com/zerobase/travel/post/service/PostService.java
Hibernate에서 **LazyInitializationException**이 발생하여 지연 로딩된 컬렉션(`dayDetails`, `itineraryVisits`)을 조회할 수 없는 문제가 발생했습니다. 이로 인해 관련 데이터를 포함한 응답 생성이 실패하였으며, 컨트롤러에 로직이 집중되어 있어 가독성과 유지보수성에도 문제가 있었습니다.
---
- **LazyInitializationException 문제**
- `fetch = FetchType.LAZY`로 설정된 연관 컬렉션(`dayDetails`, `itineraryVisits`)을 접근하려다 Hibernate 세션이 닫혀 예외가 발생.
- **컨트롤러에 로직 집중**
- `PostController.searchPosts`에서 `PostSearchCriteria` 설정 및 검증, 서비스 호출 등의 로직이 혼재되어 코드 가독성이 떨어짐.
- **LazyInitializationException 해결**
- `dayDetails`, `itineraryVisits`의 `fetch` 전략을 `FetchType.LAZY`에서 **`FetchType.EAGER`**로 변경.
- 필요한 연관 데이터를 즉시 로딩하여 LazyInitializationException 방지.
- **컨트롤러 리팩토링**
- 검색 조건 설정 로직(`PostSearchCriteria` 구성)과 페이징 설정을 컨트롤러에서 서비스로 이동.
- 컨트롤러는 요청 데이터를 단순히 서비스로 전달하고 결과만 반환하도록 설계하여 가독성과 유지보수성을 개선.
---
- 서비스 계층에서 검색 조건 검증 및 …
> 모집게시글 조회 컨트롤러 코드 리펙토링, 조회시 Lazy 로딩에서 Eager로 수정해서 조회되지 않던 문제 해결.

- travel/src/main/java/com/zerobase/travel/communities/service/CommunityManagementService.java
- travel/src/main/java/com/zerobase/travel/communities/type/ResponseCommunityDto.java
- travel/src/main/java/com/zerobase/travel/controller/ParticipationController.java
- travel/src/main/java/com/zerobase/travel/dto/ParticipationsByPostDto.java
- travel/src/main/java/com/zerobase/travel/dto/ReseponseParticipation.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationManagementService.java
- travel/src/main/java/com/zerobase/travel/service/ParticipationService.java
- travel/src/test/java/com/zerobase/travel/communities/controller/CommunityControllerTest.java
- travel/src/test/java/com/zerobase/travel/communities/service/CommunityManagementServiceTest.java
FE요청에 따라 커뮤니티 및 참여정보 조회시 유저의 프로필 정보 추가
이를 통해, BE에서 통합된 정보를 내려주어 FE 측에서 API 호출을 최소화시킴
**AS-IS**
기존 커뮤니티 및 참여정보 조회시 유저의 userID만 제공
**TO-BE**
userID 뿐만 아니라 userMbti, nickname 등 프로필의 정보를 추가하여 발송
> feat) 참여 및 커뮤니티 조회시 유저 정보 추가
